---
baseURL: 'https://suzunaan.org/'
defaultContentLanguage: 'en'
languageCode: 'en-us'
title: '鈴奈庵'
theme: 'hugo-suzu'
enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true
hasCJKLanguage: true

permalinks:
  page:
    posts: /posts/:year/:month/:slug
    music: /music/:year/:month/:slug


markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: true

outputs:
  home: ['HTML', 'ATOM']
  section: ['HTML']
  taxonomy: ['HTML']

outputFormats:
  ATOM:
    name: ATOM
    baseName: "feed"
    mediaType: "application/atom+xml"
  "schema.json":
    mediaType: "application/schema+json"

mediaTypes:
  "application/atom+xml":
    suffixes: ["atom"]
  "application/schema+json":
    suffixes: ["schema.json"]

languages:
  en:
    languageName: 'English'
    weight: 1
  it:
    languageName: 'Italiano'
    weight: 2

params:
  logo:
    filename: 'logo.svg'
    pixelart: false
  default_author: Suzunaan Contributors
  contacts:
    name: '本居 小鈴'
    email: 'librarian@suzunaan.org'
  subsites:
    - name: Git
      link: git.suzunaan.org
  subtitle: 'A ringing library.'
  webbuttons:
    - file: suzunaan.png
      alt: Suzunaan.
      link: https://suzunaan.org
    - file: no-ai/NoAi_02.svg
      alt: This website was made without using any Artificial Intelligence whatsoever.
      page: /posts/no-ai
    - file: 2hu.gif
      alt: Touhou.
    - file: nocookie.gif
      alt: This website doesn't use cookies.
    - file: neovim.gif
      alt: This website was built with neovim.
      link: https://neovim.io
    - file: transnow2.gif
      alt: Trans rights!
    - file: bunbrowser.gif
      alt: Bunny browser.

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
