---
baseURL: 'https://suzunaan.org/'
defaultContentLanguage: 'en'
languageCode: 'en-us'
title: '鈴奈庵'
theme: 'hugo-suzu'
sectionPagesMenu: 'main'

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: true

outputs:
  home: ['HTML', 'ATOM']
  section: ['HTML']
  taxonomy: ['HTML']

outputFormats:
  ATOM:
    name: ATOM
    baseName: "feed"
    mediaType: "application/atom+xml"

# Define a new ATOM media type
mediaTypes:
  "application/atom+xml":
    suffixes: ["atom"]

languages:
  en:
    languageName: 'English'
    weight: 1
  it:
    languageName: 'Italiano'
    weight: 2

params:
  logo: '/logo.svg'
  contacts:
    name: '本居 小鈴'
    email: 'librarian@suzunaan.org'
  subsites:
    - name: Git
      link: git.suzunaan.org
  subtitle: 'A ringing library.'
  webbuttons:
    - 2hu.gif
    - nocookie.gif
    - neovim.gif
    - transnow2.gif
    - bunbrowser.gif

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
