---
baseURL: 'https://suzunaan.org/'
defaultContentLanguage: 'en'
languageCode: 'en-us'
title: '鈴奈庵'
theme: 'hugo-suzu'
sectionPagesMenu: 'main'

markup:
  tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 1

languages:
  en:
    languageName: 'English'
    weight: 1
  it:
    languageName: 'Italiano'
    weight: 2

params:
  logo: '/logo.svg'

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
