name: "build"
on:
  pull_request:
  push:

jobs:
  build:
    runs-on: docker
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          ssh-known-hosts: |
            [git.suzunaan.org]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDY5ua7bhIcKW3gR7etAvdcSheMmNxjWANIwpAOg/TbEVJzVW7EZjIZHiWkKoM5VYae2l2scXGobuBFCT7V2i5XD4QwsN7EHAbO3tFkXxQYTUxrXWDhReFW3V0bJbLtS+qqY5qXLtWUTqFj7MUV1l3NGtxanSMu4aaVvtg/hi5kRUkMMnmX0Xoe5SjkSrueyVqMv9vTmkcKrXRUv6O34UZD5dVbPjC+OBZ0VwE/2XZaMcvs1iGRFLM91mCHSlMwvqmeJ9FIrx207LSpAVQJ1+McpQLbBPcaB8MH7ltV1ZjVqo7kjJlFAOlWddjNPLRWjHWbjiynizSQexSLiOCixLp6ChkQyO1s1dzca09SluR9RaP2QejWeiHc6/TpI/rECN0vp2y+HZJaFtNkb0pqgGXUWgFG+Z7StKcYKAIG4zoNWAxHS0jnHdkWcy7KLHI9GzpPJ6Qx/Q1Xd1Eco7RGRtB8Occ3VldUnG3Xft6CiFyYOJfS+LvLyrFcZnBzjqlS8T9+GTzzRa0tUh7h4OiFnSiX0FqDbYk58eM63caZdJxS6DbL/UJkN8PSEqr1hntyvtO+EYsGscWl3VcgDuh8HoZG06LiL1/cayvHGPQbmf9fbapdkoIuJyJJt0xqSS5fgc4PdzIv1zduPjVhV7CxPpvO+qyZ0WQnojYOBKHjGydU8Q==

          submodules: 'recursive'
      - uses: https://github.com/DeterminateSystems/nix-installer-action@main
      - run: nix develop --command just build
      - run: ls -la public/

      - name: Setup SSH
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p ~/.ssh
          ls -l ~/.ssh
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.DEPLOY_SSH_PRIV_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -p 3420 -T 240 -H 'suzunaan.org' > ~/.ssh/known_hosts

      - run: nix develop --command scripts/deploy.sh
        if: github.ref == 'refs/heads/main'
        env:
          RCLONE_SFTP_KEY_FILE: ~/.ssh/id_ed25519
